apiVersion: v1
kind: Service
metadata:
  name: example-controller-svc
  labels:
    app: example-controller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: example-controller
