resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: brianlobonalabs/operator-dataflow-tools-nalabs
  newTag: 1625517975591314952.0.0
