apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataflow-nalabstools-dep
  labels:
    app: dataflow-nalabstools
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dataflow-nalabstools
  template:
    metadata:
      name: dataflow-nalabstools-pod
      labels:
        app: dataflow-nalabstools
    spec:
      containers:
        - name: dataflow-nalabstools-cont
          image: "docker.io/brianlobonalabs/nginx-app1:latest"
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
