apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: example-controller-route
  labels:
    app: example-controller
spec:
  path: /
  to:
    kind: Service
    name: example-controller-svc
    weight: 100
