apiVersion: v1
kind: Service
metadata:
  name: dataflow-nalabstools-svc
  labels:
    app: dataflow-nalabstools
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: dataflow-nalabstools
