# permissions for end users to view dataflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataflow-viewer-role
rules:
- apiGroups:
  - tools.nalabs
  resources:
  - dataflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.nalabs
  resources:
  - dataflows/status
  verbs:
  - get
