# permissions for end users to edit dataflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataflow-editor-role
rules:
- apiGroups:
  - tools.nalabs
  resources:
  - dataflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.nalabs
  resources:
  - dataflows/status
  verbs:
  - get
